// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS0IAL_gHkYnHUcBQ6NZynxLKiVltfNrA',
    appId: '1:204269562942:web:b6fe465554668958fa756f',
    messagingSenderId: '204269562942',
    projectId: 'karkhanodropshipping',
    authDomain: 'karkhanodropshipping.firebaseapp.com',
    storageBucket: 'karkhanodropshipping.appspot.com',
    measurementId: 'G-PYFX5JJ4RQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKp_qdNd_9o4nzAIyoDtcM3hk1DqLLVWU',
    appId: '1:204269562942:android:c473a2df17a0fc4dfa756f',
    messagingSenderId: '204269562942',
    projectId: 'karkhanodropshipping',
    storageBucket: 'karkhanodropshipping.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWh1JSoCu0P9NRqYDmNNkqjByy8DYgJo8',
    appId: '1:204269562942:ios:f1e8fb7f5dbdae01fa756f',
    messagingSenderId: '204269562942',
    projectId: 'karkhanodropshipping',
    storageBucket: 'karkhanodropshipping.appspot.com',
    iosClientId: '204269562942-qi1c9f7nq3q8n7cbc09diul7ecac8ot6.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceStoreKarkhano',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWh1JSoCu0P9NRqYDmNNkqjByy8DYgJo8',
    appId: '1:204269562942:ios:e16d7fa2dfadf914fa756f',
    messagingSenderId: '204269562942',
    projectId: 'karkhanodropshipping',
    storageBucket: 'karkhanodropshipping.appspot.com',
    iosClientId: '204269562942-t2hggb26chhkpkjn5iugnrfif10aj09k.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceStoreKarkhano.RunnerTests',
  );
}
